name: "Build and push to ECR"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  BuildAndPushImageToECR:
    name: "Build and Push to ECR"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR 🏷
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "new-1-repo"
          IMAGE_TAG: v6
        run: |
          docker build -t $ECR_REGISTRY/new-1-repo:$IMAGE_TAG .
          docker push $ECR_REGISTRY/new-1-repo:$IMAGE_TAG
          
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 346163310511.dkr.ecr.us-west-1.amazonaws.com
          # echo "::set-output name=image::$ECR_REGISTRY/new-1-repo:$IMAGE_TAG"
          docker tag $ECR_REGISTRY/new-1-repo:$IMAGE_TAG 346163310511.dkr.ecr.us-west-1.amazonaws.com/new-1-repo:$IMAGE_TAG
          docker push 346163310511.dkr.ecr.us-west-1.amazonaws.com/new-1-repo:$IMAGE_TAG
